const currentDate = new Date();
const pegawais = [
  {
    id: 1,
    nama: "Dian Mahanata, SKM",
    nip: "19730722 199402 1 003",
    jabatan: "Kepala Bidang Sumber Daya Kesehatan",
    unitKerjaId: 1,
    tingkatanId: 4,
    pangkatId: 3,
    golonganId: 2,
    nomorRekening: "081250628584",
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 2,
    nama: "Alfrienti Linggi Kalalembang,SKM,M.Kes",
    nip: "19710417 199703 2 001",
    jabatan: "Kepala Bidang Pelayanan Kesehatan",
    unitKerjaId: 1,
    tingkatanId: 4,
    pangkatId: 2,
    golonganId: 2,
    nomorRekening: "099250628584",
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 3,
    nama: "dr. Ainun Jariah",
    nip: "19751212 200212 2 004",
    jabatan: "Kepala Bidang Pencegahan dan Pengendalian Penyakit",
    unitKerjaId: 2,
    tingkatanId: 4,
    pangkatId: 2,
    golonganId: 2,
    nomorRekening: "081250690584",
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 4,
    nama: "H.Anang Jarkani, SKM",
    nip: "19721015 199303 1 009",
    jabatan: "Sekretaris",
    unitKerjaId: 1,
    tingkatanId: 4,
    pangkatId: 2,
    golonganId: 2,
    nomorRekening: "03330628584",
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 5,
    nama: "dr. Adhisetya Dwi Saputra",
    nip: "'19850331 201403 1 003",
    jabatan: "Kepala Bidang Kesehatan Masyarakat",
    unitKerjaId: 1,
    tingkatanId: 4,
    pangkatId: 3,
    golonganId: 3,
    nomorRekening: "081250628584",
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 6,
    nama: "Amri Yulihardi, S,STP, M.Si",
    nip: "19840726 200212 1 001",
    jabatan: "Kepala Dinas Kesehatan",
    unitKerjaId: 1,
    tingkatanId: 3,
    pangkatId: 1,
    golonganId: 1,
    nomorRekening: "0332628584",
    createdAt: currentDate,
    updatedAt: currentDate,
  },

  {
    id: 7,
    nama: "Kristina, SE",
    nip: "19841006 201001 2 024",
    jabatan: "bendahara",
    unitKerjaId: 1,
    tingkatanId: 3,
    pangkatId: 1,
    golonganId: 1,
    nomorRekening: "0332628584",
    createdAt: currentDate,
    updatedAt: currentDate,
  },

  {
    id: 8,
    nama: "Ismail, SKM",
    nip: "-",
    jabatan: "bendahara",
    unitKerjaId: 1,
    tingkatanId: 3,
    pangkatId: 1,
    golonganId: 1,
    nomorRekening: "0332628584",
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 9,
    nama: "Junaidi, A.Md.Kg",
    nip: "'19941216 201903 1 011",
    jabatan: "bendahara",
    unitKerjaId: 2,
    tingkatanId: 3,
    pangkatId: 1,
    golonganId: 1,
    nomorRekening: "0332628584",
    createdAt: currentDate,
    updatedAt: currentDate,
  },
];

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("pegawais", pegawais, {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("pegawais", null, {});
  },
};
