const currentDate = new Date();
const pegawais = [
  {
    id: 1,
    nama: "Amri Yulihardi, S,STP, M.Si",
    nip: " 19840726 200212 1 001 ",
    pangkatId: 4,
    golonganId: 9,
    jabatan: "Kepala Dinas Kesehatan",
    tingkatanId: 3,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 2,
    nama: "dr. Adhisetya Dwi Saputra",
    nip: " 19850331 201403 1 003 ",
    pangkatId: 2,
    golonganId: 7,
    jabatan: "Kepala Bidang Kesehatan Masyarakat",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 3,
    nama: "Dra. Nikmawati, Apt",
    nip: "19660525 199302 2 001",
    pangkatId: 4,
    golonganId: 9,
    jabatan: "Kepala Bidang Pelayanan Kesehatan",
    tingkatanId: 3,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 4,
    nama: "H.Anang Jarkani, SKM",
    nip: "19721015 199303 1 009",
    pangkatId: 3,
    golonganId: 8,
    jabatan: "Kepala Bidang Kesehatan Masyarakat",
    tingkatanId: 3,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 5,
    nama: "dr. Ainun Jariah",
    nip: "19751212 200212 2 004",
    pangkatId: 3,
    golonganId: 8,
    jabatan: "Kepala Bidang Pencegahan dan Pengendalian Penyakit",
    tingkatanId: 3,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 6,
    nama: "dr. Nurdiana AS,M.Kes.(MARS)",
    nip: "19770712 200502 2 003",
    pangkatId: 3,
    golonganId: 8,
    jabatan: "Kepala Bidang Sumber Daya Kesehatan",
    tingkatanId: 3,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 7,
    nama: "Alfrienti Linggi Kalalembang,SKM,M.Kes",
    nip: "19710417 199703 2 001",
    pangkatId: 3,
    golonganId: 8,
    jabatan: "Administrator Kesehatan Ahli Muda",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 8,
    nama: "Agnes Linda W, SKM.M.Kes.",
    nip: "19661012 198511 2 001",
    pangkatId: 3,
    golonganId: 8,
    jabatan: "Administrator Kesehatan Ahli Muda",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 9,
    nama: "Eko Ariyanto,A.Md,Kep,SKM",
    nip: "19650524 198901 1 001",
    pangkatId: 2,
    golonganId: 7,
    jabatan: "Administrator Kesehatan Ahli Muda",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 10,
    nama: "I'timariah, SKM",
    nip: "19690505 199503 2 006 ",
    pangkatId: 2,
    golonganId: 7,
    jabatan: "Administrator Kesehatan Ahli Muda",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 11,
    nama: "Muhammad Subhan, A.Md.Kep.",
    nip: "19710918 199102 1 001",
    pangkatId: 2,
    golonganId: 7,
    jabatan: "Promosi Kesehatan dan Ilmu Perilaku Ahli Muda",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 12,
    nama: "Jumain,SKM",
    nip: "19720705 199303 1 010",
    pangkatId: 2,
    golonganId: 7,
    jabatan: "Epidemiolog Ahli Muda",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 13,
    nama: "M. Hasanudin, S.Sos.",
    nip: "19750612 200012 1 004",
    pangkatId: 2,
    golonganId: 7,
    jabatan: "Perencana Ahli Muda",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 14,
    nama: "Indra Darmawan,Apt",
    nip: "19830309 200903 1 006",
    pangkatId: 2,
    golonganId: 7,
    jabatan: "Administrator Kesehatan Ahli Muda",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 15,
    nama: "Hendrik Latif, SKM",
    nip: "19760224 200012 1 001",
    pangkatId: 2,
    golonganId: 7,
    jabatan: "Administrator Kesehatan Ahli Muda",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 16,
    nama: "Rusmalayana, SKM",
    nip: "19750312 200502 2 002",
    pangkatId: 2,
    golonganId: 7,
    jabatan: "Administrator Kesehatan Ahli Muda",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 17,
    nama: "Dian Mahanata, SKM",
    nip: "19730722 199402 1 003",
    pangkatId: 2,
    golonganId: 7,
    jabatan: "Kepala Subbag. Kepegawaian dan Umum",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 18,
    nama: "Siti Thoibah, S.Gz.,M.Kes",
    nip: "19830929 200502 2 002",
    pangkatId: 3,
    golonganId: 8,
    jabatan: "Kepala Subbag. Keuangan",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 19,
    nama: "Sulistyo Rini, Apt",
    nip: "19760410 200502 2 001",
    pangkatId: 3,
    golonganId: 8,
    jabatan: "Penyusun Rencana Kebutuhan Logistik ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 20,
    nama: "Budi Pratiwi, AMK. S.Sos",
    nip: "19691109 199402 2 001",
    pangkatId: 2,
    golonganId: 7,
    jabatan: "Pengawas Pelayanan Publik ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 21,
    nama: "Sujarwo,A.Md,Kep",
    nip: "19740319 199403 1 004",
    pangkatId: 2,
    golonganId: 7,
    jabatan: "Pengelola Program Imunisasi",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 22,
    nama: "Marliana, S.ST. M.Kes.",
    nip: "19811201 200312 2 005",
    pangkatId: 2,
    golonganId: 7,
    jabatan: "Analis Kesehatan ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 23,
    nama: "Esti Muflichah, SKM",
    nip: "19761007 200502 2 002",
    pangkatId: 2,
    golonganId: 7,
    jabatan: "Analis Pengembangan Sumber Daya Manusia Aparatur ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 24,
    nama: "Denny Afriyan Nur,SKM.M.Kes.",
    nip: "19841228 201001 1 023",
    pangkatId: 2,
    golonganId: 7,
    jabatan: "Analis Kesehatan Kerja ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 25,
    nama: "Arif Sutikyansyahhandala Putra, S.ST",
    nip: " 19820302 200604 1 005 ",
    pangkatId: 2,
    golonganId: 7,
    jabatan: "Analis Kesehatan ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 26,
    nama: "Nurulita, S.ST.Keb",
    nip: " 19740810 200003 2 001 ",
    pangkatId: 11,
    golonganId: 6,
    jabatan: "Analis Gizi ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 27,
    nama: "Baini Rahman,SKM",
    nip: " 19800408 200502 1 004 ",
    pangkatId: 11,
    golonganId: 6,
    jabatan: "Analis Kesehatan ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 28,
    nama: "Slamet Ariyanto, A..Md.Kep.",
    nip: " 19740725 199603 1 004 ",
    pangkatId: 11,
    golonganId: 6,
    jabatan: "Pengawas Monitoring dan Evaluasi Imunisasi Puskesmas ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 29,
    nama: "Karnadi, A.Md.Kep",
    nip: " 19810701 200502 1 003 ",
    pangkatId: 11,
    golonganId: 6,
    jabatan: "Pengelola Profesi Sumber Daya Manusia ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 30,
    nama: "Yusita Indrayanti, A.Md.Keb.",
    nip: " 19791114 200502 2 006 ",
    pangkatId: 11,
    golonganId: 6,
    jabatan: "Pengelola 11an Sarana dan Prasarana ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 31,
    nama: "Hj. Rusmiana, Amd.Kes.",
    nip: " 19661006 198901 2 002 ",
    pangkatId: 11,
    golonganId: 6,
    jabatan: "Administrator Kesehatan Ahli Muda",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 32,
    nama: "Fitriani Astuti, A.Md.Keb.",
    nip: " 19790506 200604 2 025 ",
    pangkatId: 11,
    golonganId: 6,
    jabatan: "Pengelola Penyakit Tidak Menular dan Kesehatan jiwa",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 33,
    nama: "Sumardin,SKM.M.Gz.",
    nip: " 19750427 200502 1 001 ",
    pangkatId: 11,
    golonganId: 6,
    jabatan: "Analis Perencanaan, Evaluasi dan Pelaporan",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 34,
    nama: "Ni Made Yuliawati,A.Md.Gizi",
    nip: " 19800711 200903 2 009 ",
    pangkatId: 11,
    golonganId: 6,
    jabatan: "Pengelola Program Gizi",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 35,
    nama: "Wujang Bayu Pamungkas, S.Kep.Ns",
    nip: " 19851230 200804 1 001 ",
    pangkatId: 11,
    golonganId: 6,
    jabatan: "Analis Penyakit Menular ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 36,
    nama: "Nurul Fa'ikah,A.Md",
    nip: " 19881129 201001 2 011 ",
    pangkatId: 10,
    golonganId: 5,
    jabatan: "Pengelola Pemberantasan Penyakit Bersumber Binatang ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 37,
    nama: "Kristina, SE",
    nip: " 19841006 201001 2 024 ",
    pangkatId: 11,
    golonganId: 6,
    jabatan: "Bendahara",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 38,
    nama: "Nor Aisyah Purnamasari, AM KL, SKM",
    nip: "  19890717 201101 2 002 ",
    pangkatId: 10,
    golonganId: 5,
    jabatan: "Analis Kesehatan ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 39,
    nama: "Rabiatul Adawiyah, AM KL",
    nip: " 19891011 201101 2 005 ",
    pangkatId: 10,
    golonganId: 5,
    jabatan: "Pengelola Pelayanan Kesehatan ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 40,
    nama: "Apt. Erick Hemawan,S.Farm.",
    nip: " 19880221 201101 1 001 ",
    pangkatId: 10,
    golonganId: 5,
    jabatan: "Analis Pengembangan Sumber Daya Manusia Aparatur ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 41,
    nama: "Tri Yuliatin,A.Md. AK",
    nip: " 19851111 200903 2 008 ",
    pangkatId: 10,
    golonganId: 5,
    jabatan: "Pengawas Pelayanan Publik ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 42,
    nama: "Arifin",
    nip: " 19710101 200212 1 017 ",
    pangkatId: 10,
    golonganId: 5,
    jabatan: "Pengadministrasi Umum ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 43,
    nama: "Rusmahyanti, SE",
    nip: " 19860719 201001 2 023 ",
    pangkatId: 10,
    golonganId: 5,
    jabatan: "Penyusun Rencana Kebutuhan Rumah tangga Perlengkapan",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 44,
    nama: "Halimatussa'diyah, Amd.Far",
    nip: " 19870717 200903 2 006 ",
    pangkatId: 10,
    golonganId: 5,
    jabatan: "Pengelola Obat dan Alat1alat Kesehatan ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 45,
    nama: "Sofiya Maulida, S.Farm",
    nip: " 19981114 202203 2 011 ",
    pangkatId: 9,
    golonganId: 4,
    jabatan: "Analis Obat dan Makanan ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 46,
    nama: "Evi Sulfianan, SKM",
    nip: " 19910308 202203 2 004 ",
    pangkatId: 9,
    golonganId: 4,
    jabatan: "Penyuluh Kesehatan dan Pencegahan Penyakit",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 47,
    nama: "Taufiq Rahman,A.Md,Kep",
    nip: " 19770313 200312 1 006 ",
    pangkatId: 9,
    golonganId: 4,
    jabatan: "Pengelola Pelayanan Kesehatan ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 48,
    nama: "Suliyah",
    nip: "  19750904 200701 2 030 ",
    pangkatId: 9,
    golonganId: 4,
    jabatan: "Pengelola Sarana Prasarana Kantor",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 49,
    nama: "Darmansyah",
    nip: " 19790512 200701 1 011 ",
    pangkatId: 9,
    golonganId: 4,
    jabatan: "Pengadministrasi Umum",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 50,
    nama: "Junaidi, A.Md.Kg",
    nip: " 19941216 201903 1 011 ",
    pangkatId: 8,
    golonganId: 3,
    jabatan: "Pengelola Data dan Informasi",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 51,
    nama: "Harini",
    nip: " 19700517 200906 2 002 ",
    pangkatId: 8,
    golonganId: 3,
    jabatan: "Pengelola Sarana Prasarana Kantor",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 52,
    nama: "Desiana, A.Md.KL",
    nip: " 19911229 201903 2 012 ",
    pangkatId: 8,
    golonganId: 3,
    jabatan: "Pengelola Kepegawaian",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 53,
    nama: "Ardiansyah",
    nip: " 19700503 200604 1 010 ",
    pangkatId: 8,
    golonganId: 3,
    jabatan: "Pengadministrasi Umum ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 54,
    nama: "Fahrurrasyuf Rizky AlFitroch, A.Md",
    nip: " 19980808 202203 1 011 ",
    pangkatId: 7,
    golonganId: 2,
    jabatan: "Pengelola Data dan Informasi",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 55,
    nama: "Farida",
    nip: " 19790801 201212 2 003 ",
    pangkatId: 7,
    golonganId: 2,
    jabatan: "Pengadministrasi Perkantoran",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 56,
    nama: "Heriani,Amd.Keb",
    nip: " 19880413 201001 2 010 ",
    pangkatId: 10,
    golonganId: 5,
    jabatan: "Pengelola Program Kesehatan Keluarga",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 57,
    nama: "Yuyun Nora Normania",
    nip: " - ",
    pangkatId: 18,
    golonganId: 1,
    jabatan: "Staf Keuangan",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 58,
    nama: "Masdalena",
    nip: " - ",
    pangkatId: 18,
    golonganId: 1,
    jabatan: "Staf Keuangan",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 59,
    nama: "Harbiansyah",
    nip: " - ",
    pangkatId: 18,
    golonganId: 1,
    jabatan: "Staf Keuangan",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 60,
    nama: "Ismail, SKM",
    nip: " - ",
    pangkatId: 18,
    golonganId: 1,
    jabatan: "Staf Perencanaan",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 61,
    nama: "Yana,SKM",
    nip: " - ",
    pangkatId: 18,
    golonganId: 1,
    jabatan: "Staf Perencanaan",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 62,
    nama: "Rizky Widyanti, S.SiT",
    nip: " - ",
    pangkatId: 18,
    golonganId: 1,
    jabatan: "Staf Perencanaan",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 63,
    nama: "Najemawati, SE",
    nip: " 19920617 201903 2 016 ",
    pangkatId: 10,
    golonganId: 5,
    jabatan: "Bendahara",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 64,
    nama: "Mini Harti",
    nip: " - ",
    pangkatId: 18,
    golonganId: 1,
    jabatan: "Staf Pengelola Kepegawaian",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 65,
    nama: "Himmatul Ulya, A.Md.Keb",
    nip: " 19850812 200903 2 008 ",
    pangkatId: 12,
    golonganId: 7,
    jabatan: "Pengelola Data dan Informasi",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 66,
    nama: "Tiara Laksmitha P, S.Farm.,Apt ",
    nip: " - ",
    pangkatId: 18,
    golonganId: 1,
    jabatan: "Administrasi Kefarmasian ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 67,
    nama: "Ade Riska Setyawati ",
    nip: " - ",
    pangkatId: 18,
    golonganId: 1,
    jabatan: "Administrasi Alkes & PKRT ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 68,
    nama: "Dewi Mayang Sari, SKM",
    nip: " - ",
    pangkatId: 18,
    golonganId: 1,
    jabatan: "Pengelola Pemberantasan Penyakit Bersumber Binatang ",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 69,
    nama: "Risna Aprianti, S.Kep.,Ns",
    nip: " - ",
    pangkatId: 18,
    golonganId: 1,
    jabatan: "Pengelola Pemberantasan Penyakit Menular Langsung",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 70,
    nama: "Lenny Suhartini Erman, SE",
    nip: " - ",
    pangkatId: 18,
    golonganId: 1,
    jabatan: "Pengelola Yankes Primer",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 71,
    nama: "Siti Fatimah, A.Md.Keb",
    nip: " - ",
    pangkatId: 18,
    golonganId: 1,
    jabatan: "Administrasi Yankestrad",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 72,
    nama: "Muhammad Akbar, A.Md.Kep",
    nip: " - ",
    pangkatId: 18,
    golonganId: 1,
    jabatan: "Staf Yankes Rujukan",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 73,
    nama: "Muhammad Abidurrahman, A.Md.Kep",
    nip: " - ",
    pangkatId: 18,
    golonganId: 1,
    jabatan: "Staf Yankes Rujukan",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 74,
    nama: "Aditya Yogi Perdana, A.Md.Kep",
    nip: " - ",
    pangkatId: 18,
    golonganId: 1,
    jabatan: "Staf Yankes Rujukan",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 75,
    nama: "Yuni Risma Dewi, A.Md.Kep",
    nip: " - ",
    pangkatId: 18,
    golonganId: 1,
    jabatan: "Staf Yankes Rujukan",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 76,
    nama: "Himmatul Ulya, A.Md.Kes",
    nip: " - ",
    pangkatId: 18,
    golonganId: 2,
    jabatan: "Staf Yankes Rujukan",
    tingkatanId: 4,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
];

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("pegawais", pegawais, {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("pegawais", null, {});
  },
};
